### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by mdbs99** [pascalaws/fpc-runtime#1]
@MFernstrom I think the name is redundant as the main repository is already about Free Pascal.
What do you think change it just to `runtime`?
If you are thinking to create others, for another language, perhaps we can rename this one as `fpc-runtime` then.

**Comment by MFernstrom** [comment]
This is just for fpc, but there will be two.

This is the core one, it's an example for compiling a specialized runtime for max performance or speciality cases.

How about "core-runtime" and the other one just "runtime"?

I believe the other one is going to be the most used one as it'll follow the same pattern as Node.js, Python etc. for use.

**Comment by mdbs99** [comment]
I don't know which stuff will contain in the other one, but I think is better having a prefix too, which will depend what stuff will be there.

I still vote this one as `fpc-runtime` for brevity.
